package(default_visibility = ["PUBLIC"])

remote_file(
    name = "kotlin",
    hashes = [
        "945adfbc9d58d1e4899de0168ee9fb0f839e181a22618852120703b4e716745a",
    ],
    url = "https://raw.githubusercontent.com/thought-machine/pleasings/b85bbd0d98e33cc2e9a01236f66d614aee95a767/kotlin/kotlin.build_defs",
)

remote_file(
    name = "maven_jars",
    hashes = [
        "cfc09768db099822774c2e678a617c864054f03a8a3950f2f10b7557ff0af4c3",
    ],
    url = "https://raw.githubusercontent.com/thought-machine/pleasings/b85bbd0d98e33cc2e9a01236f66d614aee95a767/java/maven_jars.build_defs",
)
