package(default_visibility = ["PUBLIC"])

remote_file(
    name = "kotlin",
    url = "https://raw.githubusercontent.com/thought-machine/pleasings/4a8158a65ef39e7dd9a1569fbfa1e5eec398e066/rust/rust.build_defs",
    hashes = [
        "bbfa10e522cfc870bfcbfbae6b899b770b54031a",
    ],
)
